### ISSUE TITLE
running VD.ahk throwing error on windows 11

### ISSUE THREAD

**Issue by vivekkpatel** [FuPeiJiang/VD.ahk#27]
![image](https://user-images.githubusercontent.com/60865708/211305872-179e8e8e-f91d-405d-a4dd-6acf1c078130.png)

**Comment by FuPeiJiang** [comment]
what's your ahk version ? if it's really throwing on `switch`, then you need [v1.1.31+] https://www.autohotkey.com/docs/v1/lib/Switch.htm

**Comment by vivekkpatel** [comment]
That worked, Thanks.
