### ISSUE TITLE
v2_port still uses %var% which gets flagged as an error by the VS Code ahk2 linter

### ISSUE THREAD

**Issue by tomkahn** [FuPeiJiang/VD.ahk#31]
Talking about [this linter](https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp).

For example:

`OnMessage(MsgNum, %VD.ShellMessage%.bind(this))`

Thank you for this great library, @FuPeiJiang ! 🙏

**Comment by FuPeiJiang** [comment]
@tomkahn should be fixed now, there were many mistakes on my part, other than this `%VD.ShellMessage%`
