### ISSUE TITLE
Script sending "Q" to discord | Desktop switch failure.

### ISSUE THREAD

**Issue by ozzynotwood** [FuPeiJiang/VD.ahk#45]
Hello, thanks for this script, I've needed this for a long time. I would like to report some bugs...

 When using Discord for Windows, the Numpad1, Numpad2 & Numpad3 buttons produce 2 problems when the Discord window is active:
❌ The desktop does not switch.
❌ The letter Q is sent to the Discord chat.
A "Send q" is on line 559 which may explain the Q being sent to discord.

**UPDATE**: This also happens with EmClient (email software), I suspect this will happen in more applications now.

![Bug](https://github.com/FuPeiJiang/VD.ahk/assets/48989097/a06993bb-2f18-40de-837b-06362522a652)
![Bug2](https://github.com/FuPeiJiang/VD.ahk/assets/48989097/6fd7119d-2967-4e35-994e-18ca3cfc04fa)

I also use Numpad 4-9 (so the whole numpad) & the bugs apply to all keys.

Can you please have a look at possibly fix this?

Thanks!

Others following:
@anonymous1184

**Comment by FuPeiJiang** [comment]
@ozzynotwood @anonymous1184

CreateRemoteThread works differently for 32bit apps, my oversight

try the update ? I currently have a problem where (sometimes) switching VD is slow, I want to know if it happens on your computers too

**Comment by ozzynotwood** [comment]
This now & works & is still high-speed :)
