### ISSUE TITLE
add  RemoveDesktop, CreateDesktop, IsAppIdPinned,PinAppID,UnpinAppID method use demo

### ISSUE THREAD

**Issue by MaxSherry** [FuPeiJiang/VD.ahk#6]
i want to use RemoveDesktop, CreateDesktop method to contrl remove or create desktop .  Can you add these methods.
and IsAppIdPinned,PinAppID,UnpinAppID these methods add demo to use

**Comment by MaxSherry** [comment]
![image](https://user-images.githubusercontent.com/3919535/139642550-6367660c-fb0f-42d2-a181-e09a3087c2ec.png)

**Comment by FuPeiJiang** [comment]
@MaxSherry

**Comment by MaxSherry** [comment]
❤️  u are kindhearted person, I love you, thank u
