### ISSUE TITLE
Not working on 24H2 (26100.712)

### ISSUE THREAD

**Issue by generis-it** [FuPeiJiang/VD.ahk#70]
The script throws an exception in the newest build. As this is one of my must-have tools on Windows it would be great if someone could fix this.

> Error: An exception was thrown.
> Specifically: 0xc0000005
> 	---- D:\Software\_Autohotkey\VD.ahk-2_port\VD.ah2
> 	625: Continue
> 	626: }
> ▶	627: DllCall(this.FindDesktop, "UPtr", this.IVirtualDesktopManagerInternal.Ptr, "Ptr", GUID_Desktop, "Ptr*", &IVirtualDesktop_ofWindow := 0)
> 	628: If (IVirtualDesktop_ofWindow == IVirtualDesktop)
> 	628: {
>

**Comment by FuPeiJiang** [comment]
@generis-it
does it work with the latest update ?

**Comment by generis-it** [comment]
@FuPeiJiang works! excellent, many thanks for the super fast fix.
