### ISSUE TITLE
Display window on all desktop

### ISSUE THREAD

**Issue by Sayanel01** [FuPeiJiang/VD.ahk#74]
Hi,

Is it possible using VD.ahk to set "show this window on all desktop"? Or is VD.ahk not the right tool for that?

Question asked by someone here, but the answer is not optimal :
https://www.autohotkey.com/boards/viewtopic.php?t=74849

**Comment by FuPeiJiang** [comment]
Hi @Sayanel01,
"Show this window on all desktops" corresponds to `VD.PinWindow(wintitle)`
"Show windows from this app on all desktops" corresponds to `VD.PinExe(exe_path)`

**Comment by Sayanel01** [comment]
Wonderful, thanks !

Sorry if this was in the doc, I didn't know the term "Pin"
