### ISSUE TITLE
Following Windows over several Desktops

### ISSUE THREAD

**Issue by d-duesentrip** [FuPeiJiang/VD.ahk#80]
Hi @FuPeiJiang ,

Many Many Thanks for this repo! I stumbled over it today, and it's a real efficiency game changer!! I am using it with gestures on my logitech mouse and it's just amazing.

I have one request, though: 

I am using:
> ; move window to left and follow it
> +^#left::VD.goToDesktopNum(VD.MoveWindowToRelativeDesktopNum("A", -1))
> ; move window to right and follow it
> +^#right::VD.goToDesktopNum(VD.MoveWindowToRelativeDesktopNum("A", 1))

This works great, but only for one follow operation at a time.

However, let's say I have 4 Desktops and I want to move and follow a Window from Desktop 1 to Desktop 4.

In that case, I would like to press the shortcut 3 times back-to-back, thereby cycling through the desktops and arriving together with the window at Desktop 4 in the end.

This currently doesn't work. I assume that after the first MoveWindowToRelativeDesktop() operation, somehow the focus gets lost because when clicking on the window again and then pressing the shortcut, it works once more.

Can I somehow adapt the script so several follow operations are possible?

Thank you already for your help!

**Comment by FuPeiJiang** [comment]
sorry, that was poor design,
I've changed it to this
```ahk
; move window to left and follow it
+^#left::VD.MoveWindowToRelativeDesktopNum("A", -1).follow()
; move window to right and follow it
+^#right::VD.MoveWindowToRelativeDesktopNum("A", 1).follow()
```
@daninedan does it work now ? (after updating VD.ahk)

**Comment by d-duesentrip** [comment]
Yes it does!! Great! Thank you so much!!!
